# https://github.com/vitest-dev/vscode/issues/110#issuecomment-1730788166
packages:
  - 'packages/base'
  - 'packages/starter'
  - 'packages/bridge'
  - 'packages/react'
  - 'packages/utils'
  - 'packages/wallets/*'
  - 'packages/tools'