name: Test Badge

permissions:
  contents: write

on:
  push:
    branches:
      - dev
      - master
      - feature/badge

env:
  BRANCH_NAME: 'feature/badge-json'

jobs:
  test:
    name: Generate Test Badge
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [utils]
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Run frontend CI
        uses: AElfProject/frontend-ci-action@v0.0.2
        with:
          commit-token: ${{ secrets.COMMIT_TOKEN }}
          branch-name: "feature/badge-json"
          is-monorepo: true
          package: ${{ matrix.package }}
